{
 "title": "Secoder Git",
 "tags": [ "secoder" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(secgit_commits{namespace=\"$namespace\"},path)"
    }
   },
   {
    "name": "repo",
    "label": "repo",
    "query": {
     "query": "label_values(secgit_commits{namespace=\"$namespace\"},repo)"
    }
   },
   {
    "name": "user",
    "label": "user",
    "query": {
     "query": "label_values(secgit_commits{namespace=\"$namespace\"},user)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(secgit_commits,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secgit_commits{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}",
     "legendFormat": "{{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Commits Contribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secgit_commits{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}",
     "legendFormat": "{{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Gross Lines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secgit_commits_additions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"} - secgit_commits_deletions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}",
     "legendFormat": "{{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Lines Added",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secgit_commits_additions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}",
     "legendFormat": "add {{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Lines Deleted",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "secgit_commits_deletions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}",
     "legendFormat": "add {{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(secgit_commits{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}[$__interval])",
     "legendFormat": "{{path}} - {{repo}} - {{user}}"
    }
   ]
  },
  {
   "title": "Lines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "changes(secgit_commits_additions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}[$__interval])",
     "legendFormat": "add {{path}} - {{repo}} - {{user}}"
    },
    {
     "expr": "changes(secgit_commits_deletions{namespace=\"$namespace\", job=\"exporter\", repo=~\"$repo\", path=~\"$path\", user=~\"$user\"}[$__interval]) * -1",
     "legendFormat": "del {{path}} - {{repo}} - {{user}}"
    }
   ]
  }
 ]
}