resources:
  - deployment.yaml
  - service.yaml
  - serviceMonitor.yaml
labels:
  - pairs:
      app.kubernetes.io/conponent: exporter
      app.kubernetes.io/instance: secoder
    includeSelectors: true
    includeTemplates: true
    fields:
      - group: monitoring.coreos.com
        kind: ServiceMonitor
        path: spec/selector/matchLabels
        create: true
configMapGenerator:
  - name: secgit-dashboard
    files:
      - secgit.json=dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
