apiVersion: v1
kind: Service
metadata:
  name: npm-registry
  labels:
    app.kubernetes.io/name: npm-registry
spec:
  selector:
    app.kubernetes.io/name: npm-registry
  ports:
    - name: http
      port: 4873
      targetPort: http
