apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
