apiVersion: v1
kind: Service
metadata:
  name: devpi
  labels:
    app.kubernetes.io/name: devpi
spec:
  selector:
    app.kubernetes.io/name: devpi
  ports:
    - name: http
      port: 3141
      targetPort: http
