apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciler
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: "ghcr.io/thuse-course/secoder-reconciler:latest"
          imagePullPolicy: IfNotPresent
          name: reconciler
          ports:
            - containerPort: 8000
              protocol: TCP
