resources:
  - statefulSet.yaml
  - service.yaml
  - serviceMonitor.yaml
  - rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/component: core
      app.kubernetes.io/instance: secoder
    includeSelectors: true
    includeTemplates: true
configMapGenerator:
  - name: core-dashboard
    files:
      - core.json=dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: backend
    files:
      - config.json
