apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secoder-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secoder-core
subjects:
  - kind: ServiceAccount
    name: secoder-core
    namespace: secoder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secoder-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secoder-core
subjects:
  - kind: ServiceAccount
    name: secoder-core
    namespace: secoder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secoder-core
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterrolebindings
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secoder-core
